# Generated by Django 5.2.7 on 2025-10-08 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='name',
        ),
        migrations.AddField(
            model_name='feedback',
            name='employee_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='sentiment',
            field=models.CharField(choices=[('good', 'Good'), ('neutral', 'Neutral'), ('bad', 'Bad')], default='neutral', max_length=20),
        ),
    ]
